version: '2'
services:
  app:
    build: .
    security_opt:
      - seccomp:unconfined
    entrypoint: dlv debug app -l 0.0.0.0:2345 --headless=true
    volumes:
      - ${PWD-.}:/opt/go/src/app
    ports:
      - "2345:2345"
      - "9090:9090"
    expose:
      - "2345"
      - "9090"
